version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: indiquer_engage_backend
    restart: always
    ports:
      - "9302:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=indiquer_engage_jwt_secret_key_prod_2026
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=openai/gpt-oss-120b
    volumes:
      - engage_db_data:/app/prisma

volumes:
  engage_db_data:
    driver: local
