version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: indiquer_engage_backend
    restart: always
    ports:
      - "9302:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://indiquer_user:indiquer_password@postgres:5432/indiquer_engage_prod?schema=public
      - JWT_SECRET=indiquer_engage_jwt_secret_key_prod_2026
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: indiquer_postgres
    restart: always
    environment:
      POSTGRES_USER: indiquer_user
      POSTGRES_PASSWORD: indiquer_password
      POSTGRES_DB: indiquer_engage_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
